export const VERSION = '0.2.0';
export const NS = 'http://www.w3.org/2000/svg';
export const TAGS = ['g','path','circle','ellipse','rect','line','polyline','polygon'];
export const ATTRS = ['id','d','cx','cy','r','rx','ry','x','y','x1','x2','y1','y2','width','height','points','fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','opacity','transform','data-anchor','data-origin','data-bend','data-profile'];
export const ANCHORS = ['hand','pedal-a','pedal-b'];
export const CONTRACT = `Return only <g id="animal">...</g> or JSON {"species":"...","nodes":[{"tag":"ellipse","attrs":{"cx":300,"cy":230,"rx":35,"ry":50}}]}. Canvas 640x440. Seat (285,285), body near (300,235), handle (399,224), crank (330,334), pedal radius 24. Allowed tags: ${TAGS.join(',')}. Attributes: ${ATTRS.join(',')}. No external resources, text, CSS or scripts. For moving contacts use path data-anchor="hand|pedal-a|pedal-b" data-origin="x,y" data-bend="20"; runtime replaces its d with a quadratic curve from origin to anchor. Include all three contacts, using morphology-appropriate limbs or body sections (snake has no legs). Max elements counts root and descendants. JSON wraps nodes in the animal root; nodes may have children only for g. Use unique IDs; only the root may use id animal.`;
export function promptFor(task, skill = '') {
  return `${skill ? skill.trim()+'\n\n' : ''}${task.track === 'B' ? 'Return a complete single-file HTML with a self-contained SVG animation of an animal riding a bicycle. No external dependencies. Fit the 800x560 viewport. Motion must begin automatically. Do not include explanatory text.' : CONTRACT+' Optional data-profile="joint" draws a bent two-segment limb; data-profile="wing" draws a closed wing contour. Otherwise contacts are quadratic curves.'}\nAnimal: ${task.animal}. Output budget: ${task.budget} tokens. Max SVG elements: ${task.maxElements}. ${task.requirement || ''}`;
}
